import Head from 'next/head'
import PageLayout from '@/components/PageLayout'
export default function Home() {
  return (
    <>
      <Head>
        <title>JKUSMA dinner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <PageLayout />
      </main>
    </>
  )
}
